### ISSUE TITLE
Update installation instructions w.r.t. conda-forge

### ISSUE THREAD

**Issue by MicroPhen** [MicroPhen/pyFOOMB#27]
* [ ] discriminate between easy installation from conda-forge and from source (repo)
* [ ] limit dependencies (in conda-recipe and setup-py) to minimum that is needed to run tests

**Comment by kossikater** [comment]
From checking the repo:
- numpy
- scipy
- pandas
- matplotlib
- seaborn
- joblib
- psutil
- assimulo
- pygmo

**Comment by Beaker034** [comment]
Consequently:

- seaborn-base

**Comment by MicroPhen** [comment]
closed with PR 28
